
spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver

    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true

    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group-id-taeho
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer


logging.level:
    org.hibernate.SQL: debug

